// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net.proto

package habitat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HID struct {
	UuidM                int64    `protobuf:"varint,1,opt,name=uuidM,proto3" json:"uuidM,omitempty"`
	UuidL                int64    `protobuf:"varint,2,opt,name=uuidL,proto3" json:"uuidL,omitempty"`
	Component            uint32   `protobuf:"varint,3,opt,name=component,proto3" json:"component,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HID) Reset()         { *m = HID{} }
func (m *HID) String() string { return proto.CompactTextString(m) }
func (*HID) ProtoMessage()    {}
func (*HID) Descriptor() ([]byte, []int) {
	return fileDescriptor_net_c24866ae2271c7da, []int{0}
}
func (m *HID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HID.Unmarshal(m, b)
}
func (m *HID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HID.Marshal(b, m, deterministic)
}
func (dst *HID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HID.Merge(dst, src)
}
func (m *HID) XXX_Size() int {
	return xxx_messageInfo_HID.Size(m)
}
func (m *HID) XXX_DiscardUnknown() {
	xxx_messageInfo_HID.DiscardUnknown(m)
}

var xxx_messageInfo_HID proto.InternalMessageInfo

func (m *HID) GetUuidM() int64 {
	if m != nil {
		return m.UuidM
	}
	return 0
}

func (m *HID) GetUuidL() int64 {
	if m != nil {
		return m.UuidL
	}
	return 0
}

func (m *HID) GetComponent() uint32 {
	if m != nil {
		return m.Component
	}
	return 0
}

type Packet struct {
	Source               *HID     `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	Dest                 *HID     `protobuf:"bytes,2,opt,name=Dest,proto3" json:"Dest,omitempty"`
	Origin               *HID     `protobuf:"bytes,3,opt,name=Origin,proto3" json:"Origin,omitempty"`
	FID                  uint32   `protobuf:"varint,4,opt,name=FID,proto3" json:"FID,omitempty"`
	PID                  uint32   `protobuf:"varint,5,opt,name=PID,proto3" json:"PID,omitempty"`
	M                    bool     `protobuf:"varint,6,opt,name=M,proto3" json:"M,omitempty"`
	P                    uint32   `protobuf:"varint,7,opt,name=P,proto3" json:"P,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_net_c24866ae2271c7da, []int{1}
}
func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (dst *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(dst, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetSource() *HID {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Packet) GetDest() *HID {
	if m != nil {
		return m.Dest
	}
	return nil
}

func (m *Packet) GetOrigin() *HID {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *Packet) GetFID() uint32 {
	if m != nil {
		return m.FID
	}
	return 0
}

func (m *Packet) GetPID() uint32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *Packet) GetM() bool {
	if m != nil {
		return m.M
	}
	return false
}

func (m *Packet) GetP() uint32 {
	if m != nil {
		return m.P
	}
	return 0
}

func init() {
	proto.RegisterType((*HID)(nil), "habitat.HID")
	proto.RegisterType((*Packet)(nil), "habitat.Packet")
}

func init() { proto.RegisterFile("net.proto", fileDescriptor_net_c24866ae2271c7da) }

var fileDescriptor_net_c24866ae2271c7da = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4a, 0xc4, 0x30,
	0x18, 0x85, 0xf9, 0xcd, 0x4c, 0xc6, 0xf9, 0x1d, 0x41, 0x82, 0x8b, 0x2c, 0x5c, 0x84, 0xc1, 0x45,
	0x57, 0x5d, 0xe8, 0x15, 0x82, 0x34, 0xd0, 0xd2, 0x10, 0x4f, 0xd0, 0xd6, 0xa0, 0x41, 0x4c, 0x4a,
	0x4d, 0xaf, 0xe6, 0xf9, 0x24, 0x69, 0xa5, 0xe0, 0xec, 0xf2, 0xbe, 0x2f, 0xbc, 0x17, 0x82, 0x47,
	0x6f, 0x63, 0x39, 0x4e, 0x21, 0x06, 0x76, 0xf8, 0xe8, 0x7a, 0x17, 0xbb, 0x78, 0x6e, 0x91, 0x54,
	0x4a, 0xb2, 0x7b, 0xdc, 0xcf, 0xb3, 0x7b, 0x6b, 0x38, 0x08, 0x28, 0x88, 0x59, 0xc2, 0x1f, 0xad,
	0xf9, 0xd5, 0x46, 0x6b, 0xf6, 0x80, 0xc7, 0x21, 0x7c, 0x8d, 0xc1, 0x5b, 0x1f, 0x39, 0x11, 0x50,
	0xdc, 0x9a, 0x0d, 0x9c, 0x7f, 0x00, 0xa9, 0xee, 0x86, 0x4f, 0x1b, 0xd9, 0x23, 0xd2, 0xd7, 0x30,
	0x4f, 0x83, 0xcd, 0xad, 0x37, 0x4f, 0xa7, 0x72, 0x5d, 0x2d, 0x2b, 0x25, 0xcd, 0xea, 0x98, 0xc0,
	0x9d, 0xb4, 0xdf, 0x31, 0x6f, 0xfc, 0xbf, 0x93, 0x4d, 0xea, 0x69, 0x27, 0xf7, 0xee, 0x7c, 0x5e,
	0xbb, 0xe8, 0x59, 0x1c, 0xbb, 0x43, 0xf2, 0xa2, 0x24, 0xdf, 0xe5, 0x07, 0xa5, 0x63, 0x22, 0x5a,
	0x49, 0xbe, 0x5f, 0x88, 0x56, 0x92, 0x9d, 0x10, 0x1a, 0x4e, 0x05, 0x14, 0xd7, 0x06, 0x9a, 0x94,
	0x34, 0x3f, 0x64, 0x0b, 0xba, 0xa7, 0xf9, 0x67, 0x9e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x04,
	0x5f, 0x3f, 0x74, 0x26, 0x01, 0x00, 0x00,
}
